### ISSUE TITLE
Async done missplaced

### ISSUE THREAD

**Issue by sashberd** [SomMeri/grunt-zip-to-crx#1]
Hey guys,
I found that you async callback function is not well implemented inside your code, thus,e.g.,  if after you code invoke i`d like to clean the zip file it will stack execution and will not clean the zip file. The problem is in this function: 

```
  var options, filesList, allInputFilesTripples, CrxCreatorConstructor, crxCreator, done;
**done = this.async();** 
......
  /*was changed by Alex*/
error = zipsToCrx.thickThing(options, allSrcZips, crxDestination, originalSrcZip, filesTripple.orig.dest,**done**  /*function(){}*/, function(error) {
    grunt.log.warn(error);
  });
});
```

I just provide the async done function instead of your empty anonymous function to thickThing(),

For you review.

**Comment by SomMeri** [comment]
You want to provide your own onDone/onError  function in grunt file or you want an option to delete the zip file? Or maybe both?
